### ISSUE TITLE
UnFinished Text within How To Play

### ISSUE THREAD

**Issue by ghost** [Jarrrk/HighLife-Website#1]
In how to play at the faq all of 
My vehicle disappeared. How do I find it?
My bank account shows a negative amount. What does that mean?
How long do compensations take to be paid out
Can I use GTAV modpacks?

all of them don't actually have answers to the questions 

https://highliferoleplay.net/guide

**Comment by kissanealex** [comment]
Resolved. Thanks for reporting.
