### ISSUE TITLE
"Compile Charges" button (Non-Priority)

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#12]
Feature Request: "Compile Charges" button on Citizen profiles. Upon pressing, page is brought up with all the charges that person has been charged with, and how many counts.

E.g. person has 2 sentences, one for RD, FEA, GTA. One for RD, Att. Murder, GTA, Murder

Compiled Charges: RD (2) | GTA (2) | FEA | Att. Murder | Murder

Extra: Upon pressing of "RD (2)" button, it would bring up the 4 documents of reports for those two sentences that included RD. - Arrest & Arrest Report info.

_Any questions on what I mean about any of this just lmk_

**Comment by kissanealex** [comment]
Done on next push
