### ISSUE TITLE
Small Lawyer (not) present UI bug

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#17]
Reported in these two messages, [1](https://discord.com/channels/366897352012988418/735953024694091777/905510882069598278) & [2](https://discord.com/channels/366897352012988418/735953024694091777/905529602569556079) the first time you press Lawyer Present, the time & fine doesn't update to 50% of the original like it should.

Video: https://streamable.com/4la2dx

**Comment by kissanealex** [comment]
Resolved on next deploy
