### ISSUE TITLE
Charge List Page

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#19]
Underneath "Currently Processing", add a page that lists all charges, definitions, times and fines. Furthermore, it would be great for these to be listed in a similar format as [this](https://discord.com/channels/366897352012988418/735953024694091777/907228404372369429). 

Secondly, a search bar on the page for the charges would be great, allowing us to find an individual charge easier.

**Comment by kissanealex** [comment]
Done
