### ISSUE TITLE
Dynasty8 web page QoL improvement

### ISSUE THREAD

**Issue by OffensiveExile** [Jarrrk/HighLife-Website#2]
If possible, there are three things that I'd like to see improved to the web page for the generator. 

1) Possibility to change "Agent Details" to any text we like as we frequently put "Seller Details" in there to direct potential clients to their contact information.
2) Override the image boxes with new images in the event we accidentally upload the wrong one. Currently we have to refresh the page if we mess up.
3) Removal of the white space between the menu bar and the green box as currently if you scroll down on the page even a little bit, it causes it to show in the saved image and sometimes doesn't go away after trying again. https://i.imgur.com/rDFXjpi.png

These are minor things that I would like to see added just to improve the general QoL of listing properties.

**Comment by kissanealex** [comment]
All issues addressed
