### ISSUE TITLE
Citizen Profile > Known vehicles model not showing up

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#20]
Citizen Profile > Known vehicles, hover over a plate and see that the model of the car isn't listed in "Description". The information can be found if you click the plate, however not on the citizen page.

[Discord reference](https://discord.com/channels/366897352012988418/735953024694091777/905798845844295730)

**Comment by kissanealex** [comment]
Add for all vehicles added from now on
