### ISSUE TITLE
Arrest Archive > Citizen search bug

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#21]
Currently, if you go into arrests archive > search for a citizen, chances are if you type their name, it won't show up as demonstrated in the below screenshot. It'd be great for it to work the same as in the Arrest Report page, shown in the 2nd screenshot.

![NVIDIA_Share_K42iw7JMcr](https://user-images.githubusercontent.com/65282548/141359665-bc863329-f702-43cf-955f-815123411983.png)

![image](https://user-images.githubusercontent.com/65282548/141360839-4165eed2-1478-4bdf-b02c-f905dbbbfa33.png)

**Comment by kissanealex** [comment]
Added
