### ISSUE TITLE
Deleteable citations

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#23]
To make citations deletable - This would work by allowing the Issuing officer of said citation to delete it from the issuing time > 10 minutes after, and also make non-time based deletion of citations permission-based.

I'm assuming how we'll set this up is past the 10 minutes of creation, only Supervisors can delete citations.

**Comment by kissanealex** [comment]
Done, new permission added for > 10 mins `cad-citizen-delete-citation`
