### ISSUE TITLE
Separate fine & time reductions in sentencing

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#25]
Would be great to have a separate box for both time & fine reductions, demonstrated in the screenshot below. 

![FiveM_b2372_GTAProcess_hoRjwpqnxU](https://user-images.githubusercontent.com/65282548/141498531-3c85c885-6b46-448f-9ff0-c2c8ed11586d.png)

**Comment by kissanealex** [comment]
I've done this, but you will forever be disliked for this.
