### ISSUE TITLE
Unable to filter arrests by officers/citizens/arrest ID

### ISSUE THREAD

**Issue by Kvira1** [Jarrrk/HighLife-Website#28]
When you try to filter arrests by offficers/citizens/arrest ID, it doesn't function and causes the CAD to crash at times

https://i.imgur.com/g9N7VcM.png
https://i.imgur.com/h8DLLsk.png

https://i.imgur.com/rl7CBgX.png

**Comment by kissanealex** [comment]
Fixed :)
