### ISSUE TITLE
Arrest Reports and suspects Escaping Custody

### ISSUE THREAD

**Issue by Tricer121** [Jarrrk/HighLife-Website#31]
Currently as it stands, if someone gets broken out via a hostage exchange etc, the initial arresting officer might have to 'scrap' his arrest report as to not clog up 'Currently Processing' Tab for unknown period of time.

This also means, information about the scene and evidence for the initial arrest might be lost, unless it's saved manually/locally by the initial arresting officer and communicated to the new arresting officer with DMs. (extremely unlikely)

**Suggestion**:
- add an option to put an Arrest Report '**On hold**'. 
- this would remove it from the '**Currently Processing**' Tab and move it to probably some other, new Tab. 

**Additionally**:
When creating a warrant, an officer could also have an option to select and link one of the Arrest Report that have status 'On hold' - for ease of access. 
If said suspect does get arrested in the future, new arresting officer can just click the link leading to Arrest Report by the initial arresting Officer, at which point additional information is inputted and later submitted by new arresting Officer. 

Submitting the Arrest Report would remove the 'On-Hold' status and just archive the Arrest Report like usual.

**Comment by SupperRobin6394** [comment]
Pretty sure one can add notes to a warrant, so I'd just copy-paste the arrest report's text into the warrant's information textarea

**Comment by Tricer121** [comment]
You cannot add 'notes'. There's a field for Description, which is 400 char limited and is not supposed to serve that purpose. 
It's also a field that gets displayed in the **Warrant list**.

Description should be limited to what the suspect wears and how he looks or whatever vehicles was he spotted in.

I'm aware that people have been using it like that, due to not having any other option. It feels clunky imo.

**Comment by kissanealex** [comment]
PD management decided this is not required
