### ISSUE TITLE
Citizen's criminal record is 50% duplicate info (Jail Time & Arrest Report)

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#32]
**Issue:**
Since an arrest report is mandatory, showing both 'Jail Time' and 'Arrest Report' underneath eachother in the 'Criminal Record' section of citizen information is just duplicate information and clutters up the list of it's an individual with a lot of repeated offences.

![image](https://user-images.githubusercontent.com/21952780/142604501-9e8e32c7-2510-44d3-b3a2-8adbb9efc783.png)

**Proposed solution:**
Simply removing the 'Jail Time' entry IF there is an arrest report tied to it, or not showing jail sentences altogether and ONLY showing arrest reports.
This way you will not miss out on any information, whilst allowing for more entries to be shown at once.
![image](https://user-images.githubusercontent.com/21952780/142605088-1519891e-7ba5-4b78-9c65-36d2a215de5b.png)

**Comment by kissanealex** [comment]
Actioned on next push.
