### ISSUE TITLE
Arrest warrants aren't displaying in new arrest reports

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#33]
Warrants don't show in new arrest reports.

1. Find a warranted person
2. Start new report, type person's name
3. See no warrant is attached
4. Manually add warrant, no info shows

https://imgur.com/a/XcfyXkq

**Comment by Tricer121** [comment]
Can also add as I've arrested Russi yesterday:
Upon attaching the warrant to the arrest report, charges no longer got included on their own. Had to add them in manually. 
The warrant did get served once I've published the report.

**Comment by kissanealex** [comment]
> Can also add as I've arrested Russi yesterday: Upon attaching the warrant to the arrest report, charges no longer got included on their own. Had to add them in manually. The warrant did get served once I've published the report.

This was never a feature

**Comment by kissanealex** [comment]
Resolved on next push.
