### ISSUE TITLE
Processing warrants still a little borked

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#38]
1. Set warrant
2. Go to process new > input warranted person's name
3. See the warrant(s) don't automatically popup
4. Try to type in name of the suspect, also doesn't show applicable warrants
![image](https://user-images.githubusercontent.com/65282548/143451581-4a5f0b68-270f-406f-91b2-03e6833d9df3.png)

In short: Warrants don't automatically popup & you can't search through warrants list for the person's name

**Comment by kissanealex** [comment]
Resolved on next deployment
