### ISSUE TITLE
Display number of warrants next to "View All"

### ISSUE THREAD

**Issue by Kvira1** [Jarrrk/HighLife-Website#39]
Basically display number of all the warrants combined next to "View All" area, it would also be nice if we could see the number while we're viewing the warrants

Examples:
![Untitled](https://user-images.githubusercontent.com/59372855/143781480-1b2cdb58-e9f7-4e12-bae7-6764407cff11.png)
![Untitled](https://user-images.githubusercontent.com/59372855/143781512-3500b780-7189-473a-986e-3631a1570127.png)

**Comment by kissanealex** [comment]
Live on next deploy
