### ISSUE TITLE
Property Search Inventory - New Feature

### ISSUE THREAD

**Issue by Scottehhh** [Jarrrk/HighLife-Website#40]
The ability to track the inventories of property searches through the CAD. At present they're a bit here, there and everywhere so this would massively centralise and structure things for us. For the most part it's just storing information. Shall attach the previously shown mock-up of how it should/could look.

![HOTORNOT](https://user-images.githubusercontent.com/54588704/144247509-91d62eb6-9320-4e34-a595-31060e507d0e.png)

Citizen Name - This would obviously link to their citizen profile the same way it does in the Arrest Processing page.

Search Type - A drop down selection of 'Warranted' and 'Warrantless'.
Judge Name - Text box. If Search Type is selected as 'Warrantless' then this field can be greyed out / not accessible as it wouldn't apply.
Property Address - Again, a text box.

Search Inventory - Ideally have it split into the 3 sections above. Split into 1 box for quantity of item, then another for the item name. Can start as 1 line under each with a + button if an Officer requires a new line for another item. Seems neater than 10 blank lines on every form as a starting point. Ignore the "NEW" button here, this is a mistake on the mock up.

Evidence Handling - Again, basically pulling the same feature from the Arrest Processing page where you can select a list of Officers.
Yes - Just a check box that must be checked for the form to be submitted.
Signed - Text box, also must be filled before form can be submitted.

Last but not least, a submission button I forgot to add to the mock up. This can either go below the Declaration section of to the right of the 'Signed' field.

In conjunction with this we'd need somewhere we can view a list of all Search Inventories. It would also be helpful if on a Citizen's profile we could compile the search inventory entries for that person into 1 list and then be able to click on each individual one to open the full report. Alternatively, the list function just mentioned could have a search by name filter to avoid an entirely new button being added on the citizen profile page.

We would also require 3 permissions to be set for this feature.
- Rank to File a Search Report
- Rank to View Filed Reports
- Rank to Edit Filed Reports

Thank you, don't believe I've missed anything. Hopefully this is all fleshed out enough.

**Comment by kissanealex** [comment]
Implemented.
