### ISSUE TITLE
Misc. Information easier to read

### ISSUE THREAD

**Issue by Mastro12345** [Jarrrk/HighLife-Website#41]
I am talking about this one: https://imgur.com/a/2dX9HiO

Right now it's a bit hard to read Misc Information when more than one officer has submitted a text. It can end up looking like one long text.

I suggest adding something to make each text clear, perhaps a faded thin separation line? Like the [hr][/hr] on forums, but perhaps thinner and more faded.

 If not that then at least a symbol at the start of every unique message, e.g > or •

**Comment by kissanealex** [comment]
Fixed on next update
