### ISSUE TITLE
Remove the 15 arrest limit on linking arrests to reports

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#42]
As you're aware Kisssane, with how many times we've had to reach out to get you to attach an arrest ID to a report after it can't be done by us due to the limit, this 15/20 limit of most recent arrests needs removing, please.

Ideally, a way to automate attaching an arrest to a report would be great but a band-aid solution would be to just remove the limit of the most recent 15/20 arrests

**Comment by kissanealex** [comment]
Solution implemented
