### ISSUE TITLE
Property Search Report - Citizen Name Bug

### ISSUE THREAD

**Issue by Scottehhh** [Jarrrk/HighLife-Website#44]
As shown in the image below, when on the Property Search Reports page the citizen name does not appear correctly. The hyperlink works correctly and links to their profile, but visibly it states 'Unknown'.

![image](https://user-images.githubusercontent.com/54588704/145306046-4e585a72-f6b6-4966-a3e0-0b792ef94817.png)

**Comment by kissanealex** [comment]
Fixed on next update!
