### ISSUE TITLE
LSPD CAD Issue Warrant crash

### ISSUE THREAD

**Issue by Tricer121** [Jarrrk/HighLife-Website#47]
The CAD reports a crash and makes the warrant not submittable. 

Steps: 
1) Click on **Issue Warrant** 
2) Select Citizen Profile 
3) Click on **Select a Charge** Dropdown menu
3) Crash Screen appears (have filled one out with nickname Tricer)
4) Fill out the rest of information 
5) Clicking **Publish Warrant** doesn't submit the warrant, warrant doesn't appear in Warrant List etc.

**Comment by kissanealex** [comment]
This has been fixed
