### ISSUE TITLE
Employment status on citizen profile

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#48]
Rather simple, all whitelists tied to a character could be displayed on the citizen's profile.
Quick mock-up below using HTML edit 'skills'.
This would GREATLY help us when informing employers about their employee's arrests where necessary. 
![image](https://user-images.githubusercontent.com/21952780/147603055-2e8a6994-c235-4c7f-8f88-cfebfbaaa501.png)

**Comment by kissanealex** [comment]
PD can do this themselved by editing the citizen information form. I will not populate it with DB data, sorry.
