### ISSUE TITLE
'published by' is incorrect if arrest report is published by someone that's NOT the creator of the report

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#49]
'published by' is incorrect if arrest report is published by someone that's NOT the creator of the report, that's pretty much it.

Reproduction steps;
1. Have someone make an arrest report.
2. YOU publish it
3. The arrest will state the creator as the publisher, even tho it's listed separately

**Comment by kissanealex** [comment]
This is what PD asked for,
