### ISSUE TITLE
CAD - Company owned vehicle plates shouldn't return as stolen

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#5]
Quite simple, if the vehicle is owned by a company (WL or public) it shouldn't return as stolen. As all company-owned plates have a prefix unique to them, it can be done.
Check plate
If owned by player -> return owner
if not owned -> check prefix
if prefix is known for a company then mark vehicle as 'owned by company'
If no prefix known = stolen

https://cdn.discordapp.com/attachments/540648766345183242/905402642744881152/unknown.png

**Comment by kissanealex** [comment]
Done, will be pushed on next deploy to live
