### ISSUE TITLE
CAD - Unable to publish warrants with more than 5 charges.

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#53]
Rather simple bug, Officers are unable to publish a warrant on a citizen if there's more than 5 unique charges listed on the warrant.
You can spam the 'submit' button, nothing happens, but the CAD will throw an 'unable to submit request' error message ~30 seconds after pressing the 'submit' button.
Removing charges to go 4 charges will make the officer able to submit the warrant.

**Comment by kissanealex** [comment]
this has been fixed
