### ISSUE TITLE
Los Santos City Law - Heavily Outdated

### ISSUE THREAD

**Issue by FiveMaxy** [Jarrrk/HighLife-Website#54]
The City Law link that is available on the website through the drop down menu "Information > In City Laws" is heavily out of date. Last amendment shows "1/5/21" and since then we have had more charges added but also an entire new CAD system set up which have added a lot to the system, the majority of them being "Attempted" variants of existing charges. I am unsure who is the one responsible for maintaining this system but I just thought it was worth mentioning here due to the fact that it is website related.

Public City Law document: https://docs.google.com/spreadsheets/d/e/2PACX-1vTI3OE6rptNO_k147nUCaS5ceMiib7PJdl19cMrcN2HvBBL4x9Hkf21ScyCCETGHY9WrEALRxfDrD_e/pubhtml?gid=1686514141&single=true

**Comment by kissanealex** [comment]
This has been done, just in the process of deploying!
