### ISSUE TITLE
Website - Compensations - Incorrect vehicle quantities

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#55]
Was making a compensation on a vehicle of mine, the trunk contents showed 0 as quantity on all items in the trunk.
Vehicle: C7TZYQ8G
Compensation: 6212d8c06ee643b0c706eec6

![image](https://user-images.githubusercontent.com/21952780/154870825-1ccd0614-17f6-44fe-bb09-4097d2458249.png)

**Comment by kissanealex** [comment]
Resolved on next push
