### ISSUE TITLE
CAD - Unable to filter completed warrants with ID/Citizen Name

### ISSUE THREAD

**Issue by Kvira1** [Jarrrk/HighLife-Website#56]
If you attempt to filter completed warrant by a name or a warrant ID, it won't function at all.

Basically, go to Completed Warrants, attempt to filter specific warrant by name or ID, it won't work.
![chrome_4674ValfIG](https://user-images.githubusercontent.com/59372855/155526667-5cc721bf-6daa-47d8-b82f-f5b58e482bff.png)

**Comment by kissanealex** [comment]
Fixed on next CAD push
