### ISSUE TITLE
Website - Add related staff to compensation requests

### ISSUE THREAD

**Issue by JenniWhitman** [Jarrrk/HighLife-Website#57]
Problem:
I'd like to add a field for the user to add related staff to a compensation request. This will prompt them to add the information to stop this submitting 3 tickets for 1 request because simple instructions are too difficult.
Currently: they often forget to put which staff member handled a situation
Goal: they are prompted to do so, also hopefully takes a step out of the ticket closing process so Scotteh doesn't have to manually assign comps.

Solution:
Add an **optional** field which has the title/text "Staff member who reviewed the situation/evidence" which is either:
a select field, linked to staff, which would then auto assign that compensation to that staff
or
a text field for them to write the staff name in, which would not allow auto-assign

Note:
We might also want to update the text on the page to include that evidence is required or something to that effect on top of the player v player shit.

**Comment by kissanealex** [comment]
Added an input box, don't really want to supply a list of staff :D
