### ISSUE TITLE
Morgue Inclusion - New Feature

### ISSUE THREAD

**Issue by NateGSVT** [Jarrrk/HighLife-Website#60]
Feature - Include Morgue events like arrests are currently implemented so that once an individual has been morgued, we can attach the related arrest report to them.

Reason for inclusion - Currently at this time, if an individual is to be morgued but an arrest would've been completed, there is no way to file an arrest report due to the fact that they're never sent off to jail, preventing the report from finishing. I understand that since the individual is being morgued, technically there's no reason to write a report, but since morgue times/fines are determined by their criminal actions before they pass, I figured it was still worth it to write everything up on our end to have for the database.

Suggested actions - Either include morgue events in the same way arrest events are shown in the dropdown menu so that they can be attatched to arrest reports for completion, OR, remove the need for an arrest to be necessary, and have a button/box to check that notes the event including a morgue for that individual. 

P.S. could also include some sort of implementation for removing any active warrants related to said individual, if box is checked/morgue event selected.

**Comment by kissanealex** [comment]
Will be added once we wipe :)
