### ISSUE TITLE
Arrest report warrants don't display warrant charge numbers

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#62]
After issuing a warrant with more than one count of X charge and seeing that warrant when entering that person's profile on the arrest report page, the number of counts isn't defined. This could lead to some missed charges and possibly a lot of missed fine & jail time.

See screenshots.
![chrome_aKa4L4Opaa](https://user-images.githubusercontent.com/65282548/163693345-3c94b74c-1cbc-4ae7-b956-9bf101228f27.png)
![chrome_6lzIa7FAMY](https://user-images.githubusercontent.com/65282548/163693346-85cc3a19-c035-4800-b371-e4b69eff119f.png)

**Comment by kissanealex** [comment]
Resolved on next push
