### ISSUE TITLE
When clocked into PD, arrest reports show our BCSO characters

### ISSUE THREAD

**Issue by nomi9** [Jarrrk/HighLife-Website#68]
Cleared Cache before this. 

1. Confirmed that "logged" onto the correct profile: https://i.imgur.com/v3h1r12.png
2. When checked arrest reports, shows up as the correct logged in character (Mina Senna): https://i.imgur.com/J8A6A35.png
3. When creating arrest report, BCSO character shows up (Willow Rivers): https://i.imgur.com/W9yDK6g.png

**Comment by SupperRobin6394** [comment]
Related to #67
