### ISSUE TITLE
Vehicles updating on active profiles when sold / bought / transferred

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#70]
Simply, similarly to how vehicles are logged in the "Find my car" app on the phone, when a player bugs / sells / transfers a vehicle, it logs appropriately. 

- Local sell vehicle: Remove vehicle from profile
- Transfer vehicle: Remove vehicle from old profile, add to new.
- Buy vehicle: Add vehicle to profile

I believe this requires logging profiles to characters, which was a request months back anyway.

**Alternatives**

Create a permission-based way to "search the vehicle database" - Which would essentially allow (Lt+? / DOA) to see all the vehicles someone has on their character. This would mean regular PD has to refer to the manual inputted plates for vehicles, but the higherups & investigative Officers can look deeper.

**Comment by kissanealex** [comment]
Can't seem to see this data in the db anywhere, so won't be able to supply it
