### ISSUE TITLE
CAD - Cannot delete own arrest report draft

### ISSUE THREAD

**Issue by SupperRobin6394** [Jarrrk/HighLife-Website#76]
BCSO specific, potentially.
I cannot delete a draft I made for an arrest report.

Unsure if LSPD faces the same issue.
![image](https://user-images.githubusercontent.com/21952780/182117256-325f3428-953a-4941-be48-ea660eee6b8a.png)

**Comment by Harper2000** [comment]
LSPD has the same issue.

**Comment by SupperRobin6394** [comment]
Resolved from what I've seen
