### ISSUE TITLE
Fine archive not displaying citizen names

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#8]
Fine archive doesn't display who was fined, however the individual Officer Profiles > Fines tab does

![chrome_egsdHg11Ky](https://user-images.githubusercontent.com/65282548/141139892-a87734d1-ffa9-425e-82b4-f52207dae244.png)
![chrome_gheBT8OqPi](https://user-images.githubusercontent.com/65282548/141139811-41b20a98-dcae-4e68-af4d-27f00f04b339.png)

**Comment by kissanealex** [comment]
Resolved on next push
