### ISSUE TITLE
Officer name shown as "Unknown" under citations & warnings on CAD

### ISSUE THREAD

**Issue by Kvira1** [Jarrrk/HighLife-Website#80]
When you issue a citation to a citizen, your name shows up as "Unknown"

![FiveM_b2699_GTAProcess_Waqjl9X6xi](https://user-images.githubusercontent.com/59372855/200018095-f50e3694-26d3-420e-a665-63ee325177dc.png)

**Comment by kissanealex** [comment]
Sadly can't fix old citations, but new ones are fixed
