### ISSUE TITLE
Phone Font is Skinny

### ISSUE THREAD

**Issue by sbdonslaught** [Jarrrk/HighLife-Website#88]
For some reason, the font on my phone is not skinny. It used to be nice and bold, (I'm told it still is by other people)

Issue: 
https://onslaught.ca/s/wd80i24z.png
https://onslaught.ca/s/eovifsq9.png

Should be:
https://onslaught.ca/s/r0fu2A1t.png

**Comment by kissanealex** [comment]
you problem
