### ISSUE TITLE
Active warrants displaying in archived arrest reports.

### ISSUE THREAD

**Issue by skryy99** [Jarrrk/HighLife-Website#9]
Currently, when you view an archived arrest report of a person with an active warrant, that active warrant will show on the viewed report. - The warrant should only show in archived reports for the arrest that serves said warrant.

![chrome_VG3emZM1Kl](https://user-images.githubusercontent.com/65282548/141140370-175ed36b-d413-4818-8a59-5c3c09cd9465.png)

Below: Viewing the highlighted arrest report in the above image, posted _before_ the warrant was set.
![chrome_S7jV8CaP0D](https://user-images.githubusercontent.com/65282548/141140383-7b8df193-562b-4a06-85f6-d751043d9d4c.png)

**Comment by kissanealex** [comment]
Resolved on next push
